### ISSUE TITLE
[ BUG ] The place in the top right corner of the screen is not completely covered.

### ISSUE THREAD

**Issue by DreamConnected** [PlayForm/Round#123]
But I can't reproduce it with screenshots
![1707390961605](https://github.com/RoundedCorners/Application/assets/109940850/0b559b2c-9511-411f-988a-bb2d2ad37cf9)
![1707390961610](https://github.com/RoundedCorners/Application/assets/109940850/d73b4d52-f13d-46d5-890d-bc75b961abc4)

**Comment by DreamConnected** [comment]
With new discoveries, the bug disappears every time the size is increased or decreased, and the next time the bug is added or decreased, the bug will appear every time the size is added.

**Comment by NikolaRHristov** [comment]
Yes, there are slight differences in how pixels are rendered on higher density displays.

The default setting is `23px` of roundness and gets increased or decreased by `6px` every time you click an option from the menu.

I'll try to convert it to a sliding value, so that it can be fine tuned, otherwise the scale is always:

23px
29px
35px

etc..


Thank you for your report!

**Comment by DreamConnected** [comment]
Okay, can we add a startup option in future versions? I think this feature is necessary.

**Comment by NikolaRHristov** [comment]
Are the settings not preserved?
